version: '3.7'

services:
  frontend:
    image: node:18.8
    command: sh -c "npm run dev"
    user: 'node'
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 8080:5173
    networks:
      - frontend

  backend:
    image: node:18.8
    command: npm run dev
    user: 'node'
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8081:3000
    networks:
      - backend

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: devpassword
      MYSQL_DATABASE: app
    ports:
      - 3306:3306
    networks:
      - backend

networks:
  frontend:
  backend: